# version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: aashi
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: python:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: